# Key DB password
secretKeyPassword: "F+;kF;ZWoD|B}qr~"

# Token
secretKeyAccessToken: "T*Mm:yhw+3^PnO9%cpkf"
secretKeyRefreshToken: "1U{-XU%NQdd^b+rAB6~="
tokenType: "Bearer"
tokenExpire: 3600

# AWS Access S3 Bucket Media Files
awsAccessKeyId: "AKIAQQ5XHU3GYXG6VTOB"
awsSecretAccessKey: "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"
awsToken: ""
